workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "TheMovieDB.xcodeproj"
          XCODE_SCHEME: "TheMovieDB"
    scripts:
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.1'
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - alfian.official.mail@gmail.com
